### DISCUSSION TITLE
Container failing, what am I doing wrong?

### DISCUSSION THREAD

**Discussion by LazerDickMcCheese** [ghomasHudson/Jellyfin-Auto-Collections#105] [Q&A]
Here's the log:

```
2025/05/29 13:46:03 | stderr | in "/app/config/config.yaml", line 13, column 2
2025/05/29 13:46:03 | stderr | expected <block end>, but found '<block mapping start>'
2025/05/29 13:46:03 | stderr | in "/app/config/config.yaml", line 6, column 1
2025/05/29 13:46:03 | stderr | yaml.parser.ParserError: while parsing a block mapping
2025/05/29 13:46:03 | stderr | raise ParserError("while parsing a block mapping", self.marks[-1],
2025/05/29 13:46:03 | stderr | File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
2025/05/29 13:46:03 | stderr | self.current_event = self.state()
2025/05/29 13:46:03 | stderr | File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
2025/05/29 13:46:03 | stderr | while not self.check_event(MappingEndEvent):
2025/05/29 13:46:03 | stderr | File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
2025/05/29 13:46:03 | stderr | node = self.compose_mapping_node(anchor)
2025/05/29 13:46:03 | stderr | File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
2025/05/29 13:46:03 | stderr | node = self.compose_node(None, None)
2025/05/29 13:46:03 | stderr | File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
2025/05/29 13:46:03 | stderr | document = self.compose_document()
2025/05/29 13:46:03 | stderr | File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
2025/05/29 13:46:03 | stderr | node = self.get_single_node()
2025/05/29 13:46:03 | stderr | File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
2025/05/29 13:46:03 | stderr | return loader.get_single_data()
2025/05/29 13:46:03 | stderr | File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
2025/05/29 13:46:03 | stderr | return yaml.load(conf_data, Loader=loader)
2025/05/29 13:46:03 | stderr | File "/usr/local/lib/python3.10/site-packages/pyaml_env/parse_config.py", line 110, in parse_config
2025/05/29 13:46:03 | stderr | config = parse_config(args.config, default_value=None)
2025/05/29 13:46:03 | stderr | File "/app/main.py", line 29, in <module>
2025/05/29 13:46:03 | stderr | Traceback (most recent call last):
```

And the config:

```yaml
crontab: !ENV ${CRONTAB}   # If set, this runs the script on a schedule. Should be in crontab format e.g. `0 0 5 * *`
timezone: !ENV ${TZ}   # Timezone the crontab operates on.
jellyfin:
  server_url: [redacted]
  api_key: [redacted]        # Create an API key by going to: Admin>Dashboard>Advanced>API Keys
  user_id: [redacted]       #ID of your jellyfin user. Found in the URL when you navigate to your user in the Dashboard.

 jellyseerr:
   server_url: [redacted]
   email: [redacted]
   password: [redacted]
   user_type: local

plugins:
  imdb_chart:
    enabled: true
    list_ids:
      - top
      - boxoffice
      - moviemeter
      - tvmeter
    clear_collection: true   # If set, this empties out the collection before re-adding. Useful for lists which change often.
  imdb_list:
    enabled: true
    list_ids:
      - ls055592025
      - ls068305490
      - ls087301829
  letterboxd:
    enabled: true
    imdb_id_filter: true # Uses the imdb id for better matching. This does slow the script down though!
    list_ids:
      - fcbarcelona/list/movies-everyone-should-watch-at-least-once
      - dave/list/official-top-250-narrative-feature-films
  mdblist:
    enabled: true
    list_ids:
      - hdlists/crazy-plot-twists
  tspdt:
    enabled: true
    list_ids:
      - 1000-greatest-films
  trakt:
    enabled: true
    list_ids:
      - "movies/boxoffice"
      - "shows/popular"
      - walt-disney-animated-feature-films
      - "[redacted]"   # Custom list ID for a user's list. Peek at the HTML source of the list page to find <input id="list-id" type="hidden" value="20124699">
    client_id: [redacted] # Trakt API client ID. Create an app at https://trakt.tv/oauth/applications/new and copy the client ID
    client_secret: [redacted]  # Trakt API client secret. Create an app at https://trakt.tv/oauth/applications/new and copy the client secret
  arr:
    enabled: true
    server_configs:
      - base_url: [redacted]
        api_key: [redacted]
      - base_url: [redacted]
        api_key: [redacted]
    list_ids:
      - my_tag
  jellyfin_api:
    enabled: false
    list_ids:
      - minCriticRating: ["9"]
        limit: ["3"]
        sortBy: ["Random"]
        includeItemTypes: ["Movie"]
        list_name: "Random Highly-Rated Movies" # Optional human-readable collection name
        list_desc: "A random selection of highly popular movies"
      - genres: ["Mystery"]
  popular_movies: 
    enabled: false
    list_ids:
      - movies
  criterion_channel:
    enabled: false
    list_ids:
      - hong-kong-hits
      - british-new-wave
  listmania:
    enabled: false
    list_ids:
      - wonderful-movies-you-might-have-missed
      - 40-must-have-mafiacrime-movies
  bfi:
    enabled: true
    list_ids:
      - 10-great-films-featuring-dual-performances
      - 5-things-watch-this-weekend-24-26-january-2025
```
