### ISSUE TITLE
How to set up trakt

### ISSUE THREAD

**Issue by Druidblack** [ghomasHudson/Jellyfin-Auto-Collections#45]
How do I set up trakt? I added the client_id and client_secret generated earlier for another project. Currently, no applications use this data.

After restarting the container. The scan stops at the creation of movies/box office. 

Do I need any other settings to work with trakt?

**Comment by Druidblack** [comment]
yes

**Comment by ghomasHudson** [comment]
Hmm. Here's the process I went through.

1. Go to https://trakt.tv/oauth/applications/new and fill out the form.
2. Press submit. On the next page, copy the Client ID and Client Secret.
![image](https://github.com/ghomasHudson/Jellyfin-Auto-Collections/assets/13795113/2520eea4-00e6-4e97-891e-859a9582e92a)
3. Add these to the config file:
```yaml
  trakt:
    enabled: false
    list_ids:
      - "movies/boxoffice"
      - "shows/popular"
    client_id: 3fa9e48c2708818943b733b8da7424eb24e138bb99f91d68c6ede798c0f79f69
    client_secret: 1b90dd8530bfbdb1c91de6fbb6a87f9595f34fb6e957e16a8a79047e8aa0bdca
```
4. Run the script. It will provide you a device code and link to follow. Enter the code at the link and the script will now be authenticated and create the lists.
