### ISSUE TITLE
Support Lists Retrieved via Jellyfin API

### ISSUE THREAD

**Issue by consier** [ghomasHudson/Jellyfin-Auto-Collections#52]
It would be a valuable enhancement to introduce an additional plugin that allows to interact with the Jellyfin API, enabling the automatic creation of movie collections in Jellyfin based on specific criteria.

allows for collections based on `tag`, `parentId`, `genre`, etc.
[https://api.jellyfin.org/#tag/Items/operation/GetItems](url)

**Comment by ghomasHudson** [comment]
Good idea - I'll work on a jellyfin plugin which takes some query as input.

**Comment by ghomasHudson** [comment]
Have added a `jellyfin_api` plugin which allows you to enter any api query as the list id, e.g.:

```yaml
plugins:
  ...
  jellyfin_api:
    enabled: true
    list_ids:
      - tags: ["film noir"]
      - genres: ["Mystery"]
```

which will make 2 collections:
- Items which have the tag "film noir"
- Items which have the genre "Mystery"

You can combine these by listing multiple for each list (e.g. you could make a collection which contains film noir, mystery movies released in 1956 with a rating > 95%).
