### ISSUE TITLE
[feature] Request missing collection items from Jellyseerr

### ISSUE THREAD

**Issue by andyhawks** [ghomasHudson/Jellyfin-Auto-Collections#58]
I would love to see a feature added where missing items from a collection can be passed as requests to Jellyseerr! 

An intermediary feature request that would also be helpful would be to log missing collection items to a text file.

**Comment by ghomasHudson** [comment]
Have added some basic support for this now. Try adding this to your config:

```yaml
jellyfin:
  ...
jellyseerr:
  server_url: https://jellyseerr.example.com
  api_key: AAaaAAAaAAA0AaAaAaaaa...
...
plugins:
  ....
```

Let me know if there are any problems.

**Comment by Druidblack** [comment]
Good afternoon. Tell me, the new jellyseerr feature will make requests from which user? If it is from the administrator, then this is bad, because the administrator may have the option to automatically accept the request. 
But I would like to see and confirm before the script adds 10 or 100 movies to my collection.

**Comment by ghomasHudson** [comment]
Yes you're right it was authenticating as admin which auto-accepts all the requests. I've added the option to authenticate as any user now:

```yaml
jellyseerr:
  server_url: https://jellyseerr.example.com
  email: collections@example.com
  password: mypassword
  user_type: local
```

Might be worth making a seperate local user just for this script so you can seperate the requests.
