### ISSUE TITLE
Ability to exclude libraries from generating collections

### ISSUE THREAD

**Issue by kandykarter** [ghomasHudson/Jellyfin-Auto-Collections#64]
I have a secondary library in my Jellyfin instance that connects to Jellyseer, allowing my users to request content that I'm not interested in having in my main library. Of course, when I run jellyfin-auto-collections to build my Collections library, movies from both the Prime library and the Secondary library are being added to collections, but I'd prefer to just have items from the Prime library show up. 

Is there a way to make this happen?

**Comment by ghomasHudson** [comment]
Yes that should be possible. The search just uses the jellyfin [GetItems](https://api.jellyfin.org/#tag/Items/operation/GetItems) API call, so any query parameter there can be filtered on.

We could add a `jellyfin.global_query_parameters` config option to make this request more general-purpose. Then you could specify the Prime library with the `parentId` parameter.

**Comment by ghomasHudson** [comment]
Done. Let me know how it works, e.g.:

```yaml
jellyfin:
  server_url: https://jellyfin.example.com
  api_key: ...
  user_id: ...
  query_parameters:
    parentId: f137a2dd21cce1b98aa5c0f6bf02a805 # copy this from the url when you browse to the Prime library
```

Let me know if you have any problems.
