### ISSUE TITLE
Wrong movies added to collections

### ISSUE THREAD

**Issue by alvitali** [ghomasHudson/Jellyfin-Auto-Collections#71]
Hi,

Thank you for creating this tool! This is amazing.

However, recently I noticed a whole bunch of movies in collections which shouldn't be there. All of my collections are created from Letterboxd lists. The titles of the wrongfully added movies do not show up in Jellyfin-Auto-Collections' logs.

When I delete the automatically created collections and restart JAC, the same wrong movies are added to the same collections again.

Is this an error with Jellyfin's metadata / matching? Jellyfin/JAC's log output doesn't tell me much about what exactly is happening, and where the mismatches come from. I'd be happy for some pointers on how to troubleshoot this - I'm happy to provide more information!

Cheers

**Comment by ghomasHudson** [comment]
I appreciate it's a little difficult with the logs (something that definitely needs work I agree), but can you give me the letterbox url and a couple of the wrongfully added movies that you spotted?

I'll try and recreate your issue.

**Comment by alvitali** [comment]
For sure! The list which first made me aware of the issue is this one: https://letterboxd.com/stautis/list/good-films-90-minutes-or-less/ as a lot of the movies in the collection were more than 90 minutes long. A few examples of movies not in the list, but always added to the collection:

- All We Imagine as Light (2024)
- The Girl with the Needle (2024)
- The Count of Monte Cristo (2024)
- The Little Mermaid (2023)
- Measures of Men (2023)
- Neptune Frost (2022)
- Argentina 1985 (2022)
- Ghostbusters: Afterlife (2021)
- No Time to Die (2021)
- Violet Evergarden: The Movie (2021)
- The Invisible Man (2020)

These are all the movies between 2020-2024 that shouldn't be in the collection - easy to find spot, as they all are longer than 90 minutes - but it's a similar picture with the other lists I added from Letterboxd. It seems all the movies present in my library are also correctly added to the collection they belong to - there's just a lot of additional movies that shouldn't be there.

Tell me if there's anything else I can do to help

**Comment by ghomasHudson** [comment]
Thanks - will try and replicate it now.

Have you tried adding `imdb_id_filter` to the letterboxd config? (I appreciate it's terribly documented):
```yaml
  letterboxd:
    enabled: true
    imdb_id_filter: true
    list_ids:
      - ...
```

This will find the imdb id for each movie which should lead to more precise matching (but takes longer)

**Comment by alvitali** [comment]
yeah, i added both
```
imdb_id_filter: true
    clear_collection: true
```
while first trying to troubleshoot the issue, however that didn't help

**Comment by ghomasHudson** [comment]
OK, I've tried to reproduce your problem and haven't had much success.

I've added more debugging output in an update, so would be helpful if you could:
- update your docker image (assuming you're using docker)
- Add `LOG_LEVEL=debug`, e.g.
```yaml
jellyfin-auto-collections:
    image: ghcr.io/ghomashudson/jellyfin-auto-collections:latest
    ...
    environment:
      - LOG_LEVEL=debug
```

This should then start outputting exactly which movies are getting matched, e.g.:

```
 | INFO     | utils.jellyfin:add_item_to_collection:186 - Added Airplane! to collection
 | DEBUG    | utils.jellyfin:add_item_to_collection:187 - 	List item: {'title': 'Airplane!', 'media_type': ['Movie'], 'release_year': '1980', 'imdb_id': 'tt0080339'}
 | DEBUG    | utils.jellyfin:add_item_to_collection:188 - 	Matched JF item: {'Name': 'Airplane!', 'ServerId': '...', 'Id': '...', 'Container': 'mkv,webm', 'PremiereDate': '1980-07-02T00:00:00.0000000Z', 'CriticRating': 97, 'OfficialRating': 'GB-12A', 'ChannelId': None, 'CommunityRating': 7.7, 'RunTimeTicks': ..., 'ProductionYear': 1980, 'ProviderIds': {'Tmdb': '813', 'Imdb': 'tt0080339', 'TmdbCollection': '91663'}, 'IsFolder': False, 'Type': 'Movie',...
```

This will hopefully tell us where the extra items are coming from.

**Comment by ghomasHudson** [comment]
Pushed a few updates which might fix this bug. See if it works.

**Comment by alvitali** [comment]
Sorry for only getting back to you so late @ghomasHudson

Sadly, i'm still having the same issue on the current latest release, with the same mismatched titles. Thank you for pointing me to inspect the debug logs though, making the issue apparent:

```
2025-04-28 01:02:57.169 | INFO     | utils.jellyfin:add_item_to_collection:187 - Added Time to Die to collection
2025-04-28 01:02:57.169 | DEBUG    | utils.jellyfin:add_item_to_collection:188 - 	List item: {'title': 'Time to Die', 'media_type': ['Movie'], 'release_year': '1966'}
2025-04-28 01:02:57.169 | DEBUG    | utils.jellyfin:add_item_to_collection:189 - 	Matched JF item: {'Name': 'No Time to Die', 'ServerId': 'aeafc3c9ae414ae9b251dd8106b9b428', 'Id': '86dba42f899a2081861112433e96afb2', 'HasSubtitles': True, 'Container': 'mkv', 'PremiereDate': '2021-09-29T00:00:00.0000000Z', 'CriticRating': 83, 'OfficialRating': 'PG-13', 'ChannelId': None, 'CommunityRating': 7.4, 'RunTimeTicks': 98138220000, 'ProductionYear': 2021, 'ProviderIds': {'Imdb': 'tt2382320', 'Tmdb': '370172', 'TmdbCollection': '645'}, 'IsFolder': False, 'Type': 'Movie', 'UserData': {'PlaybackPositionTicks': 0, 'PlayCount': 0, 'IsFavorite': False, 'Played': False, 'Key': '370172', 'ItemId': '00000000000000000000000000000000'}, 'VideoType': 'VideoFile', 'ImageBlurHashes': {}, 'LocationType': 'FileSystem', 'MediaType': 'Video'}
```
It seems like the matching logic matches the full title of the collection release to the same string present in any library release's title, thus matching titles which contain the full title of the wanted release as part of their name if – I assume – the full match isn't present in the media library.

The same seems to be true for all the other mismatches I'm experiencing, like:
`Imagine` is in the collection, but not the library -> `All We Imagine as Light` is wrongfully added
`Cristo` -> `The Count of Monte-Cristo`
etc.

It seems the script doesn't check for the release year either, is this correct?

**Comment by alvitali** [comment]
The letterboxd list which caused the mismatches above is this one: https://letterboxd.com/stautis/list/good-films-90-minutes-or-less/

For completeness, here's my entire configuration:
<details>
<summary><b>docker-compose.yml</b></summary>

```yaml
name: jellyfin-auto-collections
services:
  jellyfin-auto-collections:
    image: ghcr.io/ghomashudson/jellyfin-auto-collections:latest
    container_name: jellyfin-auto-collections
    security_opt:
      - no-new-privileges:true
    # user: ${UID}:${GID}
    networks:
      - jellyfin-backend
    environment:
      - CRONTAB=0 0 * * *
      - TZ=${TZ}
      - LOG_LEVEL=debug
      - JELLYFIN_SERVER_URL=http://jellyfin:8096
      - JELLYFIN_API_KEY=${JF_API_KEY}
      - JELLYFIN_USER_ID=${JF_USER_ID}
    volumes:
      - ${DATA_DIR}/auto-collections/config:/app/config
    restart: unless-stopped

networks:
  jellyfin-backend:
    name: jellyfin-backend
    external: true
```

</details>

<details>
<summary><b>config/config.yaml</b></summary>

```yaml
crontab: !ENV ${CRONTAB}   # If set, this runs the script on a schedule. Should be in crontab format e.g. `0 0 5 * *`
timezone: !ENV ${TZ}   # Timezone the crontab operates on.
jellyfin:
  server_url: !ENV ${JELLYFIN_SERVER_URL:http://jellyfin:8096}
  api_key: !ENV ${JELLYFIN_API_KEY}         # Create an API key by going to: Admin>Dashboard>Advanced>API Keys
  user_id: !ENV ${JELLYFIN_USER_ID}         #ID of your jellyfin user. Found in the URL when you navigate to your user in the Dashboard.

plugins:
  imdb_chart:
    enabled: false
    list_ids:
      - top
      - boxoffice
      - moviemeter
      - tvmeter
    clear_collection: true   # If set, this empties out the collection before re-adding. Useful for lists which change often.
  imdb_list:
    enabled: false
    imdb_id_filter: false # Uses the imdb id for better matching. This does slow the script down though!
    list_ids:
      - ls055592025
      - ls068305490
      - ls087301829
  letterboxd:
    enabled: true
    imdb_id_filter: true
    clear_collection: true
    list_ids:
      - dave/list/official-top-250-narrative-feature-films
      - jack/list/official-top-250-documentary-films/
      - fcbarcelona/list/movies-everyone-should-watch-at-least-once
      - etolkin/list/filmlist:28697007
      - darkestparadise/list/definition-of-girly-classics/
      - magrosleau/list/psychosexual-dramas-nihilistic-fever-dreams/
      - andredenervaux/list/youre-not-the-same-person-once-the-film-has/
      - adaydreaming/list/feeling-lost-in-your-20s/
      - stautis/list/good-films-90-minutes-or-less/
  mdblist:
    enabled: false
    list_ids:
      - hdlists/crazy-plot-twists
  tspdt:
    enabled: false
    list_ids:
      - 1000-greatest-films
  trakt:
    enabled: false
    list_ids:
      - "movies/boxoffice"
      - "shows/popular"
      - walt-disney-animated-feature-films
      - "20124699"   # Custom list ID for a user's list. Peek at the HTML source of the list page to find <input id="list-id" type="hidden" value="20124699">
    client_id: aaaaaaa111111111 # Trakt API client ID. Create an app at https://trakt.tv/oauth/applications/new and copy the client ID
    client_secret: aaaaaaa111111111  # Trakt API client secret. Create an app at https://trakt.tv/oauth/applications/new and copy the client secret
  jellyfin_api:
    enabled: false
    list_ids:
      - minCriticRating: ["9"]
        limit: ["3"]
        sortBy: ["Random"]
        includeItemTypes: ["Movie"]
        list_name: "Random Highly-Rated Movies" # Optional human-readable collection name
        list_desc: "A random selection of highly popular movies"
      - genres: ["Mystery"]
```

</details>
