### ISSUE TITLE
Add poster image config options

### ISSUE THREAD

**Issue by ghomasHudson** [ghomasHudson/Jellyfin-Auto-Collections#73]
Expose some of the poster image config options.

E.g.

```yaml
poster_generation:
  google_font_css_url:
  shadow_size: 8
  overlay_padding: 50
  overlay_radius: 30
  overlay_color: [0,0,0,180]
```
