### ISSUE TITLE
Collection based on Radarr/Sonarr tags

### ISSUE THREAD

**Issue by tweety-tv** [ghomasHudson/Jellyfin-Auto-Collections#76]
I use radarr/sonarr as the main controller of my collection and I use tags in there. 
It would be nice to be able to create collection based of those tags.

Would you be open to this idea? I can create a plugin for it and make a pull request.

**Comment by ghomasHudson** [comment]
Great idea - have pushed a basic implementation now.

Looks like they use the same API so maybe it made sense to create a generic `arr` plugin. You can add the config:

```yaml
arr:
    enabled: true
    server_configs:
      - base_url: https://radarr.example.com
        api_key: aaaabbbbcccc
      - base_url: https://sonarr.example.com
        api_key: aaaabbbbcccc
    list_ids:
      - my_tag_name
```

At some point we should support an "auto" setting to retrieve all the available tags but would require a wider re-write.
