### ISSUE TITLE
Jellyfin APi issue with tags

### ISSUE THREAD

**Issue by p37307** [ghomasHudson/Jellyfin-Auto-Collections#77]
I am curious about the text added to the collection.xml file when using the jellyfin API as the list.  Is this the expected behavior?

I used this setting
```
 jellyfin_api:
    enabled: true
    list_ids:
      - genres: ["Mystery"]
        limit: ["100"]
        sortBy: ["Random"]
        includeItemTypes: ["Movie"]
        list_name: "Highly-Rated Mystery Movies" # Optional human-readable collection name
        list_desc: "Highly-Rated Mystery Movies"


```

The collection xml wrote this:

`<Overview>Movies which match the jellyfin API query: {'genres': ['Mystery'], 'limit': ['100'], 'sortBy': ['Random'], 'includeItemTypes': ['Movie'], 'list_name': 'Highly-Rated Mystery Movies', 'list_desc': 'Highly-Rated Mystery Movies'}</Overview>
  <LocalTitle>Highly-Rated Mystery Movies</LocalTitle>`

and also, in the tags, it wrote this

` <Tags>
    <Tag>Jellyfin-Auto-Collections</Tag>
    <Tag>{"genres": ["Mystery"], "limit": ["100"], "sortBy": ["Random"], "includeItemTypes": ["Movie"]}</Tag>
    <Tag>jellyfin_api</Tag>
  </Tags>`

![Image](https://github.com/user-attachments/assets/fb2a6b91-35b5-41fd-99ba-67840250bfba)
