### ISSUE TITLE
LLM-based lists

### ISSUE THREAD

**Issue by ghomasHudson** [ghomasHudson/Jellyfin-Auto-Collections#79]
Can we make lists which call a litellm model with a prompt. Config could look something like:

```yaml
llm:
   model: "openai/gpt-4o"
   list_ids:
     - "a cosy movie night to watch child-friendly superhero films"
     - "films with a happy ending"
     - "movies set in space"
```
