### ISSUE TITLE
Add option list_name and list_desc for all

### ISSUE THREAD

**Issue by tweety-tv** [ghomasHudson/Jellyfin-Auto-Collections#91]
With the jellyfin_api you can add an optional list_name/list_desc, it would be nice to be able to do this with all the others aswell.
Sometimes the list names are not really what I want or are very long.

Idea:
```
list_ids:
      - list_id: 123456789
        list_name: "Random Highly-Rated Movies" # Optional human-readable collection name
        list_desc: "A random selection of highly popular movies"
```
