### ISSUE TITLE
Suggestion for improved docs examples

### ISSUE THREAD

**Issue by ecker00** [ghomasHudson/Jellyfin-Auto-Collections#95]
I think most do not realize how powerful the API approach is. I would include this is the examples: https://github.com/ghomasHudson/Jellyfin-Auto-Collections/wiki/Plugin-%E2%80%90-Jellyfin-API

```yml
plugins:
 jellyfin_api:
    enabled: true
    clear_collection: true
    list_ids:
      # By free text search
      - searchTerm: "Asterix"
        list_name: "Asterix & Obelix"
        includeItemTypes: ["Movie"]
      # By studio
      - studios: ["Marvel Studios","Marvel Entertainment"]
        list_name: "Studio: Marvel"
        includeItemTypes: ["Movie"]
     # By year
      - years: [2025]
        list_name: "Prod.Year: 2025"
        includeItemTypes: ["Movie"]

```
